import datetime
from typing import TYPE_CHECKING

from model.graph.vector import Vector
from outputParser.randomnessVector import RandomnessCounter
from model.graph.types.instance_type import InstanceType
from model.graph.types.wire_type import WireType
from model.graph.wire import Wire
from args import get_args
from version import get_version
if TYPE_CHECKING:
    from model.graph.main import Graph

class OutputParser:
    @staticmethod
    def run(graph: "Graph", output_file_path: str) -> None:
        INDENT_STRING = "    ";
        random_bit_count = sum(instance.randomBitCount for instance in graph.instances.values() if instance.randomBitCount is not None)
        wire_optimize_cache: dict[Wire, bool] = {};

        with open(output_file_path, "w") as f:
            input_wires = graph.get_wires_and_vectors_by_type(WireType.INPUT);
            output_wires = graph.get_wires_and_vectors_by_type(WireType.OUTPUT);
            args = get_args();
            f.write(f"// Generated by Unrail version {get_version()} on {datetime.datetime.now(datetime.timezone.utc).isoformat()}\n");
            f.write(f"// File: {args.file}\n");
            f.write("// For testbench check, configure the parameters like this:\n");
            f.write(f"// F2B Algorithm: {"Disabled" if args.disable_f2b else "Enabled"}\n");
            f.write(f"// B2F Algorithm: {"Disabled" if args.disable_b2f else "Enabled"}\n");
            f.write(f"// Random Bit Count: {random_bit_count}\n");
            f.write("\n");
            f.write(f"module unrail_module (\n{INDENT_STRING}")
            first = True;
            for wire in input_wires:
                if not first:
                    f.write(", ")

                if isinstance(wire, Vector):
                    f.write(f"unvectored_{wire.name}")
                else:
                    f.write(wire.name)

                first = False

            if graph.clock_wire is not None:
                if not first:
                    f.write(", ")
                f.write(graph.clock_wire)
                first = False

            if graph.precharge_wire is not None:
                if not first:
                    f.write(", ")
                f.write(graph.precharge_wire)
                first = False

            if graph.randomness_wire is not None and random_bit_count > 0:
                if not first:
                    f.write(", ")
                f.write("unvectored_" + graph.randomness_wire)
                first = False

            for wire in output_wires:
                if not first:
                    f.write(", ")
                if isinstance(wire, Vector):
                    f.write(f"unvectored_{wire.name}")
                else:
                    f.write(wire.name)
                first = False

            f.write("\n")
            f.write(");\n")

            f.write(f"{INDENT_STRING}parameter integer security_order = 1;\n")
            f.write(f"{INDENT_STRING}parameter integer d =  security_order + 1;\n")
            f.write("\n")

            # IO Definitions
            f.write(INDENT_STRING + "// IO Definitions\n");
            input_vectors: list[Vector] = [];
            for wire in input_wires:
                if isinstance(wire, Vector):
                    f.write(f"{INDENT_STRING}input [{(wire.index + 1)}*{"(d-1)" if OutputParser._is_wire_optimized(wire, wire_optimize_cache) else "2*(d-1)"}:0] unvectored_{wire.name}; // Vector [{wire.index}:0]")
                    input_vectors.append(wire);
                else:
                    f.write(f"{INDENT_STRING}input [{("d-1" if OutputParser._is_wire_optimized(wire, wire_optimize_cache) else "2*(d-1)")}:0] {wire.name};")
                f.write("\n")

            if graph.clock_wire is not None:
                f.write(f"{INDENT_STRING}input {graph.clock_wire}; // Clock\n")
            if graph.precharge_wire is not None:
                f.write(f"{INDENT_STRING}input [d-2:0] {graph.precharge_wire}; // Precharge\n")
            if graph.randomness_wire is not None and random_bit_count > 0:
                f.write(f"{INDENT_STRING}input [(2*(d*(d-1))/2)*{random_bit_count}-1:0] unvectored_{graph.randomness_wire}; // Randomness\n")
            
            output_vectors: list[Vector] = [];
            for wire in output_wires:
                if isinstance(wire, Vector):
                    f.write(f"{INDENT_STRING}output [{(wire.index + 1)}*{("(d-1)" if OutputParser._is_wire_optimized(wire, wire_optimize_cache) else "2*(d-1)")}:0] unvectored_{wire.name}; // Vector [{wire.index}:0]")
                    output_vectors.append(wire);
                else:
                    f.write(f"{INDENT_STRING}output [{("d-1" if OutputParser._is_wire_optimized(wire, wire_optimize_cache) else "2*(d-1)")}:0] {wire.name};")
                f.write("\n")

            f.write("\n")
            
            # Wire definitions
            f.write(INDENT_STRING + "// Wire definitions\n");
            if graph.randomness_wire is not None and random_bit_count > 0:
                f.write(f"{INDENT_STRING}wire [(2*(d*(d-1))/2)*{random_bit_count}-1:0] unvectored_{graph.randomness_wire};\n")
                f.write(f"{INDENT_STRING}wire [2*(d*(d-1))/2-1:0] {graph.randomness_wire} [{random_bit_count-1}:0];\n")

            for wire in graph.get_wires_and_vectors():
                f.write(f"{INDENT_STRING}wire [{("d-1" if OutputParser._is_wire_optimized(wire, wire_optimize_cache) else "2*(d-1)")}:0] {wire.name}")
                if isinstance(wire, Vector):
                    f.write(f" [{wire.index}:0];\n")
                else:
                    f.write(";\n")

            io_vectors: list[Vector] = input_vectors + output_vectors;
            for vector in io_vectors:
                f.write(f"{INDENT_STRING}wire [{(vector.index + 1)}*{("(d-1)" if OutputParser._is_wire_optimized(vector, wire_optimize_cache) else "2*(d-1)")}:0] unvectored_{vector.name};\n")

            f.write("\n");

            # Unvectored wire assignments
            f.write(INDENT_STRING + "// Unvectored wire assignments\n");
            for vector in input_vectors:
                for i in range(vector.index + 1):
                    f.write(f"{INDENT_STRING}assign {vector.name}[{i}] = unvectored_{vector.name}[{(i)}*{("d+d-1" if OutputParser._is_wire_optimized(vector, wire_optimize_cache) else "(2*(d-1)+1)+(2*(d-1))")}:{i}*{("d" if OutputParser._is_wire_optimized(vector, wire_optimize_cache) else "(2*(d-1)+1)")}];\n")
            for vector in output_vectors:
                for i in range(vector.index + 1):
                    f.write(f"{INDENT_STRING}assign unvectored_{vector.name}[{(i)}*{("d+d-1" if OutputParser._is_wire_optimized(vector, wire_optimize_cache) else "(2*(d-1)+1)+(2*(d-1))")}:{i}*{("d" if OutputParser._is_wire_optimized(vector, wire_optimize_cache) else "(2*(d-1)+1)")}] = {vector.name}[{i}];\n")

            f.write("\n");


            # Generate variable (used by the randomness mapping and the dual-to-single-rail mappings)
            has_mappings = any(instance.type == InstanceType.MAPPING for instance in graph.instances.values());
            if (graph.randomness_wire is not None and random_bit_count > 0) or has_mappings:
                f.write(INDENT_STRING + "genvar i;\n")
                f.write("\n");

            # Randomness Input Mapping
            if graph.randomness_wire is not None and random_bit_count > 0:
                f.write(INDENT_STRING + "// Randomness Input Mapping\n");
                f.write(INDENT_STRING + "generate\n")
                f.write(INDENT_STRING*2 + f"for (i = 0; i < {random_bit_count}; i=i+1) begin : loop_randomness_mapping\n")
                f.write(INDENT_STRING*3 + f"assign {graph.randomness_wire}[i]  = unvectored_{graph.randomness_wire}[(i+1)*(2*(d*(d-1))/2)-1:i*(2*(d*(d-1))/2)];\n")
                f.write(INDENT_STRING*2 + "end\n")
                f.write(INDENT_STRING + "endgenerate\n")
                f.write("\n");

            # Instance definitions
            f.write(INDENT_STRING + "// Instance definitions\n");
            random_bit_counter = RandomnessCounter(graph.randomness_wire)

            for instance in graph.instances.values():
                instance.set_config("security_order", "security_order")
                f.write(INDENT_STRING + instance.print(graph.clock_wire, graph.precharge_wire, random_bit_counter) + "\n")
                
            f.write("\n")
            f.write("endmodule\n")

    @staticmethod
    def _is_wire_optimized(wire: Wire, wire_optimize_cache: dict[Wire, bool]) -> bool:
        if wire in wire_optimize_cache:
            return wire_optimize_cache[wire];

        args = get_args()
        
        if wire.type == WireType.INPUT:
            wire_optimize_cache[wire] = not args.disable_f2b
            return not args.disable_f2b

        if wire.type == WireType.OUTPUT:
            wire_optimize_cache[wire] = not args.disable_b2f
            return not args.disable_b2f

        wire_optimize_cache[wire] = wire.from_instance.optimized
        return wire.from_instance.optimized

        
